<?php

namespace AppBundle\Repository;

/**
 * VersionProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
